version: '3.8'

services:
  frontend:
    build: ./chatapp
    ports:
      - "80:80"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql-db
      DB_USER: chatuser
      DB_PASSWORD: chatpass
      DB_NAME: chatappdb
      DB_PORT: 3306
    depends_on:
      - db


  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chatappdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
    ports:
      - "3306:3306"
